language: dart

dart:
  - stable
  # - dev

dart_task:
  - test: --platform vm

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache

# addons:
#   postgresql: '9.6'
#   apt:
#     packages:
#     - postgresql-9.6-postgis-2.3
services:
  - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test