language: dart

dart:
  - stable
  # - dev

dart_task:
  - test: --platform vm

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
 directories:
   - $HOME/.pub-cache

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-10
      - postgresql-10-postgis-2.4
      - postgresql-10-postgis-2.4-scripts
      - postgis
env:
  - PGPORT=5432
  - PGVERSION=10
sudo: false
# services:
#   - postgresql
before_script:
  - psql -c 'create database test;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d test