name: dart_postgis
description: A module to support postgis.
version: 0.2.1
homepage: https://github.com/moovida/dart_postgis
repository: https://github.com/moovida/dart_postgis
issue_tracker: https://github.com/moovida/dart_postgis/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  #  path: ^1.7.0

  dart_hydrologis_db: ^0.7.4
    # path: ../dart_hydrologis_db/
    #  git:
    #    url: https://github.com/moovida/dart_hydrologis_db.git

  dart_jts: ^0.2.0
  #    git:
  #      url: https://github.com/moovida/dart_jts.git

  # MIT
  proj4dart: ^2.0.0

  dart_hydrologis_utils: ^0.6.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
